include: 
  - "airflow_settings_base.yaml"
  # if in "airflow_settings_base_2.yaml" there is a keys that exist in 
  # airflow_settings_base.yaml - they will be overwritted
  - "airflow_settings_base_2.yaml"

airflow:
  connections:
    - id: 'own-dev-connection'
      type: fs
  pools:
    - name: 'own-dev-pool'
      slots: 110
      description: 'special dev pool'
      include_deferred: false
  variables:
    - key: 'own-dev-key'
      value: 'own-dev-value'
      description: ''
