include: 
  - "airflow_settings_base.yaml"
  # if in "airflow_settings_base_2.yaml" there is a keys that exist in 
  # airflow_settings_base.yaml - they will be overwritted
  - "airflow_settings_base_2.yaml"

airflow:
  connections: []   
  pools:
    - name: Deferred Test Pool
      slots: 12
      description: Deferred pool
      include_deferred: true
    - name: Default
      slots: 120
      description: null
      include_deferred: false
  variables:
    - key: 2v
      value: '{"some": "json"}'
      description:
    - key: 3v
      value: '["value", "weird but ok"]'
      description: '["some description", "ok"]'
    - key: 1v
      value: aaaaa
      description: null
